import { cp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));

export async function renderPage(directory = root, file = 'index.template.html', parents = []) {
    const path = resolve(directory, file);
    if (!path.startsWith(resolve(directory) + sep)) throw new Error(`Include outside site: ${file}`);
    if (parents.includes(path)) throw new Error(`Circular include: ${file}`);

    const source = (await readFile(path, 'utf8')).replace(/\r\n/g, '\n');
    const pattern = /<div data-include="([^"]+)"><\/div>/g;
    let html = '';
    let cursor = 0;
    for (const match of source.matchAll(pattern)) {
        html += source.slice(cursor, match.index);
        html += await renderPage(directory, match[1], [...parents, path]);
        cursor = match.index + match[0].length;
    }
    html += source.slice(cursor);
    if (html.includes('data-include=')) throw new Error(`Unresolved include in ${file}`);
    return html;
}

export async function build({ pages = false, check = false } = {}) {
    const html = '<!-- Generated by npm run build. Edit index.template.html and partials/. -->\n'
        + await renderPage();
    const output = resolve(root, 'index.html');
    if (check) {
        const existing = (await readFile(output, 'utf8')).replace(/\r\n/g, '\n');
        if (existing !== html) throw new Error('index.html is out of date. Run npm run build.');
        return;
    }
    // Render everything successfully before replacing the deployable page.
    await writeFile(output, html);
    if (pages) {
        const site = resolve(root, '_site');
        await mkdir(site, { recursive: true });
        await writeFile(resolve(site, 'index.html'), html);
        for (const entry of ['assets', 'styles', 'scripts/main.js', 'scripts/modules']) {
            const destination = resolve(site, entry);
            await mkdir(dirname(destination), { recursive: true });
            await cp(resolve(root, entry), destination, { recursive: true });
        }
    }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    await build({ pages: process.argv.includes('--pages'), check: process.argv.includes('--check') });
    console.log(process.argv.includes('--check') ? 'Generated HTML is current.' : 'Built static index.html.');
}
