name: Link Check

on:
  schedule:
    - cron: "0 14 * * 1"
  workflow_dispatch:

jobs:
  lychee:
    name: Check links in repo files
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --accept 200,206,429
            .
